[package]
name = "game_engine_wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28"
env_logger = "0.11.3"
log = "0.4"
wgpu = "0.18"
pollster = "0.3.0"
glam = "0.25.0"
bytemuck = {version = "1.14.3", features = ["derive, extern_crate_alloc, extern_crate_std"]}
